spring:
  jackson:
    default-property-inclusion: non-null
  application:
    name: DailyAutism
  datasource:
    url: jdbc:mysql://localhost:3306/dailyautism
    username: teste
    password: '#Teste123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    repositories.enabled: true
    database: mysql

api:
  security:
    token:
      secret: ${JWT_SECRET:#HeatCliff789)Viviane1208##Julia0204#Emmanuel1305}